INSERT INTO RUN (RUNID, INS, RUNTIME,NUMTWEET,API,APIQUERY) VALUES (1, CURRENT_TIMESTAMP(),10,5,'http://localhost:8080', '?track=trump');
INSERT INTO TWEET (MESSAGEID, CREATIONDATE, MESSAGETEXT) VALUES (1, CURRENT_TIMESTAMP(), 'This is a tweet');
INSERT INTO USER_TWEET (USERID, MESSAGEID,CREATIONDATE,USERNAME,USERSCREENNAME, RUNID) VALUES (1, 1, CURRENT_TIMESTAMP(), 'JhonnyNoPapa', 'Jhonny',1);