INSERT INTO RUN (RUNID, INS, RUNTIME,NUMTWEET,API,APIQUERY) VALUES (1, CURRENT_TIMESTAMP(),10,5,'http://localhost:8080', '?track=trump');
INSERT INTO TWEET_RUN (ID, RUNID, CREATIONDATE, MESSAGETEXT) VALUES (1, 1, CURRENT_TIMESTAMP(), 'This is a tweet');
INSERT INTO USER_TWEET_RUN (USERID, MESSAGEID,CREATIONDATE,USERNAME,USERSCREENNAME) VALUES (1, 1, CURRENT_TIMESTAMP(), 'JhonnyNoPapa', 'Jhonny');